### ISSUE TITLE
Quite a few things.

### ISSUE THREAD

**Issue by legendofmiracles** [elkowar/Auswahl#1]
1. when running, it returns this error (i have the syntax file in my config dir, in case you're wondering): 
```
IO error:
No such file or directory (os error 2)
```
2. cargo test fails on the second test
3. i made a aur package, with my own aur packager creation tool. Should i upload it?

**Comment by elkowar** [comment]
I'll look into the errors later, haven't looked at this project for a good while now. The AUR package should probably only be published _after_ it actually works ;D

**Comment by legendofmiracles** [comment]
Well its would be a  git package, so there wouldn't really be anything wrong with publishing it.

**Comment by elkowar** [comment]
would a good git package not still rely on tags or at least a certain commit? just getting `master` would never register updates in the package-managers, would it?
You would have to at least to an update after i fixed stuff, so there's no point in publishing a broken package right now

**Comment by legendofmiracles** [comment]
You're right, But as far as i know, its not normal to "freeze" a aur git package to a certain commit. And normally it is best practice to have a good, and clean master branch, and instead push unfinished, not working code to a "development" git branch, 
Because of the updates. 
The normal way on how to do it, is whenever a new release comes, to also increment the version number of the git release. So that every person who has it, also updates.

**Comment by elkowar** [comment]
exactly, normally you'd use a release tag for this (and once i fixed the issues, I'll probably do one, now that there is interest in having this packaged).

**Comment by legendofmiracles** [comment]
Well i just wanted to try this out, because i am a sucker for rofi menus.
And coincidentally i just wrote a aur packager, so i just thought i'd let it have a shot at this package.

**Comment by elkowar** [comment]
Tests are fixed now! Can you try running it again? I've changed the config file resolution logic, but i'm not sure if it fixes your issue

**Comment by legendofmiracles** [comment]
The tests complete successful. And the program also doesn't return an error, when running.

**Comment by legendofmiracles** [comment]
Works like a charm. Really awesome application!
